name: CI Pipeline - TP 3

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Caso queira teste'
        required: true
        type: boolean
        default: true
      run_lint:
        description: 'Caso queira lint'
        required: true
        type: boolean
        default: true
  push:
    branches: [ main, dev ]
    paths:
      - 'TP1/devcalc/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'TP1/devcalc/**'

jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Faz o checkout do código
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - uses: actions/checkout@v3
      - name: Instala o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Executa o build com Maven
        run: mvn clean install -DskipTests
        working-directory: TP1/devcalc

  reuse-lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs: build
    with:
      run_tests: ${{ inputs.run_tests }}
      run_lint: ${{ inputs.run_lint }}

  package:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Instala o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cria o .jar com Maven
        run: mvn package -DskipTests
        working-directory: TP1/devcalc

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-22.04
    environment: dev
    needs: [build, reuse-lint-and-test, package]
    steps:
      - name: Deploy para DEV
        run: 'echo "Deploy para DEV com var: ${{ vars.APP_MODE }} e ${{ vars.SUPPORT_EMAIL }}"'

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    environment: prod
    needs: [build, reuse-lint-and-test, package]
    steps:
      - name: Deploy para PROD
        run: 'echo "Deploy para PROD com segredo: ${{ secrets.PROD_SECRET }}"'
