name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'TP1/devcalc/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'TP1/devcalc/**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build com Maven
        run: mvn clean install -DskipTests
        working-directory: TP1/devcalc

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Executar testes
        run: mvn test
        working-directory: TP1/devcalc
