name: Issue da Variável Ausente

on: [workflow_dispatch]

permissions:
  issues: write

jobs:
  check-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica se APP_MODE está definida
        id: verificar
        run: |
          if [ -z "${{ vars.APP_MODE }}" ]; then
            echo "ausente=true" >> "$GITHUB_OUTPUT"
          else
            echo "ausente=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Criar a issue
        if: steps.verificar.outputs.ausente == 'true'
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{
                "title": "Variável APP_MODE ausente",
                "body": "O pipeline identificou que a variável APP_MODE não está definida no repositório.",
                "labels": ["bug", "pipeline"]
              }'
