name: Hello Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem
        run: echo "Pipeline iniciado com sucesso"
